### ISSUE TITLE
Not an issue but a comment about the README

### ISSUE THREAD

**Issue by lalo** [tlack/vino#5]
"There's a "secret" web interface for the Explore pane that can be accessed without login via your web browser: http://vine.co/explore . I'm a bit puzzled about what this is needed for or why they implemented the system this way. Alas, all the links are using proprietary in-app URIs"

The vine.co/explore link is used for the explore functionality on the app itself, the explore on the app is not native code and it is just a webview loading this page, the links are in-app URIs for this reason also, since it is meant for this page to be only loaded by a webview embedded on the app under the explore tab. Hope I could explain correctly.

**Comment by hannesvdvreken** [comment]
Make it a pull request instead ;-)

**Comment by lalo** [comment]
made it a pull request
